In [4]:
import numpy as np
import matplotlib.pyplot as plt
import random


n = 3
a = np.arange(n*3.0).reshape(n,3)
a.reshape(n,3)

for x in range(0,n):
    for y in range(0,3):
        a[x][y]=random.random()

print("Before whitewash")
print(a)

def whitewash(x):

    for x in range(0,n):
        for y in range(0,3):
            a[x][y]= (a[x][y] + 1)/2
    
    print("After whitewash")
    print(a)
    plt.imshow(a,origin="lower",cmap='gray',interpolation='nearest')
    plt.show()
    return


whitewash(a)


Before whitewash
[[ 0.89129468  0.05633427  0.02117705]
 [ 0.36024001  0.19633529  0.09961232]
 [ 0.82889063  0.21986829  0.30268071]]
After whitewash
[[ 0.94564734  0.52816714  0.51058852]
 [ 0.68012     0.59816764  0.54980616]
 [ 0.91444531  0.60993414  0.65134036]]
